CREATE TABLE [dbo].[LikeTag] (
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [TagId]  UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_LikeTag] PRIMARY KEY CLUSTERED ([UserId] ASC, [TagId] ASC),
    CONSTRAINT [FK_LikeTag_Tag_TagId] FOREIGN KEY ([TagId]) REFERENCES [dbo].[Tag] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_LikeTag_User_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_LikeTag_TagId]
    ON [dbo].[LikeTag]([TagId] ASC);

